CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE;
--
CREATE CACHED TABLE PUBLIC.DEVICES(
    ID BIGINT NOT NULL,
    DETECTION_ID VARCHAR(255) NOT NULL,
    FRIENDLY_NAME VARCHAR(255),
    CONNECTED BOOLEAN NOT NULL,
    LAST_STATE_CHANGE TIMESTAMP NOT NULL
);
ALTER TABLE PUBLIC.DEVICES ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);
CREATE CACHED TABLE PUBLIC.DEVICE_DETAILS(
    ID BIGINT NOT NULL,
    K VARCHAR(255) NOT NULL,
    V VARCHAR(255) NOT NULL,
);
ALTER TABLE PUBLIC.DEVICE_DETAILS ADD CONSTRAINT PUBLIC.CONSTRAINT_4C PRIMARY KEY(ID, K);
--
CREATE CACHED TABLE PUBLIC.RELAYS(
    DEVICE_ID BIGINT NOT NULL,
    CLOSED BOOLEAN NOT NULL,
    LAST_STATE_CHANGE TIMESTAMP NOT NULL
);
ALTER TABLE PUBLIC.RELAYS ADD CONSTRAINT PUBLIC.CONSTRAINT_8F PRIMARY KEY(DEVICE_ID);
--
CREATE CACHED TABLE PUBLIC.APPLIANCE_DETECTOR(
    DEVICE_ID BIGINT NOT NULL,
    IS_ON BOOLEAN NOT NULL,
    LAST_STATE_CHANGE TIMESTAMP NOT NULL,
    MAX_ON_SECS INTEGER NOT NULL,
    MIN_WATTS FLOAT NOT NULL,
    OFF_DELAY_SECS INTEGER NOT NULL
);
ALTER TABLE PUBLIC.APPLIANCE_DETECTOR ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(DEVICE_ID);
--
ALTER TABLE PUBLIC.DEVICES ADD CONSTRAINT PUBLIC.UK_SQSB8EIG3WAMUWCO461PX4IRF UNIQUE(DETECTION_ID);
ALTER TABLE PUBLIC.APPLIANCE_DETECTOR ADD CONSTRAINT PUBLIC.FK5FWI54N84TGOS4XY6O7LQE971 FOREIGN KEY(DEVICE_ID) REFERENCES PUBLIC.DEVICES(ID) NOCHECK;
ALTER TABLE PUBLIC.RELAYS ADD CONSTRAINT PUBLIC.FKOT6F1NRCAY8IJSQNRJVXUJT9M FOREIGN KEY(DEVICE_ID) REFERENCES PUBLIC.DEVICES(ID) NOCHECK;
ALTER TABLE PUBLIC.DEVICE_DETAILS ADD CONSTRAINT PUBLIC.FKJDRUIQDYHOIV8B208FKM1FBOU FOREIGN KEY(ID) REFERENCES PUBLIC.DEVICES(ID) NOCHECK;